"use client";

import { useState } from "react";
import { SpeakButton } from "@/components/SpeakButton";
import { Icon } from "@/components/icons";
import { TEMPLATE_FALLBACK_LABEL } from "@/lib/copy";

interface Brief {
  summary: string;
  nextStep: string;
  talkingPoints: string[];
  risk: "low" | "medium" | "high";
  source: "ai" | "template";
}

const RISK: Record<string, string> = {
  low: "bg-success/15 text-success",
  medium: "bg-warn/15 text-warn",
  high: "bg-danger/15 text-danger",
};

export function AiBrief({ dealId, version }: { dealId: string; version: string }) {
  const [brief, setBrief] = useState<Brief | null>(null);
  // The deal fingerprint the current brief was generated against. When the deal
  // changes (stage/value/new activity) the page re-renders with a new `version`,
  // so a brief generated against the old one is flagged stale rather than left to
  // silently contradict the deal (e.g. still saying "New Lead" after a move).
  const [generatedVersion, setGeneratedVersion] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const stale = brief !== null && generatedVersion !== version;

  async function generate() {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(`/api/ai/brief`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ dealId }),
      });
      const body = await res.json();
      if (!res.ok) throw new Error(body.error ?? "Failed");
      setBrief(body);
      setGeneratedVersion(version);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="card border-brand/30">
      <div className="mb-3 flex items-center justify-between">
        <h2 className="flex items-center gap-2 font-semibold text-fg"><Icon name="autopilot" size={16} className="text-brand" /> AI Brief</h2>
        <div className="flex items-center gap-2">
          {brief && <SpeakButton text={`${brief.summary} Next step: ${brief.nextStep}. ${brief.talkingPoints.join(". ")}`} label="Brief" />}
          {brief && <span className={`pill ${RISK[brief.risk]}`}>{brief.risk} risk</span>}
        </div>
      </div>

      {!brief ? (
        <button
          onClick={generate}
          disabled={busy}
          className="w-full rounded-lg border border-brand/40 bg-brand-soft/30 px-3 py-2 text-sm font-medium text-brand transition hover:bg-brand-soft/50 disabled:opacity-50"
        >
          {busy ? "Analyzing deal…" : "Generate brief"}
        </button>
      ) : (
        <div className="space-y-3 text-sm">
          {stale && (
            <p className="flex items-center gap-2 rounded-lg border border-warn/40 bg-warn/10 px-3 py-2 text-xs text-warn">
              <Icon name="recall" size={13} /> This deal changed since the brief was written — regenerate for the latest.
            </p>
          )}
          <p className="text-fg">{brief.summary}</p>
          <div>
            <p className="stat-label">Next best step</p>
            <p className="mt-1 text-fg">{brief.nextStep}</p>
          </div>
          <div>
            <p className="stat-label">Talking points</p>
            <ul className="mt-1 space-y-1">
              {brief.talkingPoints.map((p, i) => (
                <li key={i} className="flex gap-2 text-muted"><span className="text-brand">•</span>{p}</li>
              ))}
            </ul>
          </div>
          <div className="flex items-center justify-between pt-1">
            <span className="text-[11px] text-muted">{brief.source === "ai" ? "Generated by Claude" : TEMPLATE_FALLBACK_LABEL}</span>
            <button onClick={generate} disabled={busy} className={`text-xs hover:underline disabled:opacity-50 ${stale ? "font-semibold text-warn" : "text-brand"}`}>{busy ? "…" : "Regenerate"}</button>
          </div>
        </div>
      )}

      {error && <p className="mt-2 rounded-lg border border-danger/40 bg-danger/10 px-3 py-2 text-xs text-danger">{error}</p>}
    </section>
  );
}
